#!/usr/bin/env node
const fs	= require( "fs" );
const qrdecode	= require( "node-qrdecode" );

const die = function( msg ){
	console.log( msg );
	process.exit(1);
};
const fileToRead = process.argv[2];

qrdecode( fileToRead ).then( ( data ) => {
	console.log( data );
}, die );
